// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_7mYp3V8UzAYzEBY5t9m_dMJGzuRSKLw',
    appId: '1:779643400412:web:2559501766f4e2bb820419',
    messagingSenderId: '779643400412',
    projectId: 'chat-swipelab',
    authDomain: 'chat-swipelab.firebaseapp.com',
    storageBucket: 'chat-swipelab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRBWG3s9Loe3RVVclQKDVP5AV8fbcHyLM',
    appId: '1:779643400412:android:614bde9ed9f7c1eb820419',
    messagingSenderId: '779643400412',
    projectId: 'chat-swipelab',
    storageBucket: 'chat-swipelab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPB-18kPRkS9oDdDQxLYINTrucbPYkP6g',
    appId: '1:779643400412:ios:7501439c5e900f3a820419',
    messagingSenderId: '779643400412',
    projectId: 'chat-swipelab',
    storageBucket: 'chat-swipelab.firebasestorage.app',
    iosBundleId: 'com.swipelab.chat.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPB-18kPRkS9oDdDQxLYINTrucbPYkP6g',
    appId: '1:779643400412:ios:7501439c5e900f3a820419',
    messagingSenderId: '779643400412',
    projectId: 'chat-swipelab',
    storageBucket: 'chat-swipelab.firebasestorage.app',
    iosBundleId: 'com.swipelab.chat.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_7mYp3V8UzAYzEBY5t9m_dMJGzuRSKLw',
    appId: '1:779643400412:web:8f1dce11047c988c820419',
    messagingSenderId: '779643400412',
    projectId: 'chat-swipelab',
    authDomain: 'chat-swipelab.firebaseapp.com',
    storageBucket: 'chat-swipelab.firebasestorage.app',
  );

}