name: app
description: "Chat"
publish_to: 'none'

version: 1.0.10+10010

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  sqflite: ^2.4.2
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  stated: # 3.0.1
    path: ../../stated

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
