name: app
description: "Chat"
publish_to: 'none'

version: 1.0.10+10010

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  sqflite: ^2.4.2
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  stated: # 3.0.1
    path: ../../stated

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

  fonts:
    - family: Unna
      fonts:
        - asset: assets/fonts/Unna/Unna-Regular.ttf
        - asset: assets/fonts/Unna/Unna-Italic.ttf
          style: italic
        - asset: assets/fonts/Unna/Unna-Bold.ttf
          weight: 900
        - asset: assets/fonts/Unna/Unna-BoldItalic.ttf
          weight: 900
          style: italic
    - family: Arvo
      fonts:
        - asset: assets/fonts/Arvo/Arvo-Regular.ttf
        - asset: assets/fonts/Arvo/Arvo-Italic.ttf
          style: italic
        - asset: assets/fonts/Arvo/Arvo-Bold.ttf
          weight: 900
        - asset: assets/fonts/Arvo/Arvo-BoldItalic.ttf
          weight: 900
          style: italic
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
